name: Test rules
on:
  push:
    paths:
      - 'firestore.rules'
      - '__tests__/rules.ts'
  pull_request:
    paths:
      - 'firestore.rules'
      - '__tests__/rules.ts'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test-rules
